feature: artist create art
dldvpr-Project/localart pull request #27
Opened 2022-11-22 16:26 UTC by Dldvlpr

feature: an artist can create artCard.

2022-11-22 16:31 UTC, aldaitzwild requested changes

2022-11-22 16:31 UTC, aldaitzwild commented on src/Controller/ArtCardController.php
> +    #[Security("is_granted('ROLE_ADMIN') and is_granted('ROLE_ARTIST")]
I think it's a OR

2022-11-23 08:57 UTC, Dldvlpr commented on src/Controller/ArtCardController.php
> +    #[Security("is_granted('ROLE_ADMIN') and is_granted('ROLE_ARTIST")]
modify "and" by "or"

2022-12-02 08:38 UTC, aldaitzwild approved these changes

2022-12-02 08:38 UTC, merged